# Uncomment the next line to define a global platform for your project

platform :ios, '8.0'

target 'KYEncryptDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'GTMBase64', '~> 1.0.0'

  # Pods for KYEncryptDemo

  target 'KYEncryptDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KYEncryptDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
